version: "3.8"

services:
  api_service:
    build: ./api_service
    ports:
      - "5000:5000"
    depends_on:
      - user_service

  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
