openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Регистрация нового пользователя
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Пользователь зарегистрирован
  /login:
    post:
      summary: Авторизация пользователя
  /profile:
    get:
      summary: Получение профиля пользователя
    put:
      summary: Обновление профиля пользователя
